import Head from 'next/head';
import * as React from 'react';

import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {
  NextUIProvider,
  Container,Row, Col,
  Button,
  Input,
  Spacer,
  Link,
  Card,
  Grid,
  useTheme, Text
} from '@nextui-org/react';
import { Iconly } from 'react-iconly'
export default function Home() {
  
  const { theme } = useTheme();
  const colors = [
    'primary',
    'secondary',
    'success',
    'warning',
    'error',
    'gradient'
    
  ];
  const MockItem = ({text}) => {
    return (
        <div height={100}>
            <Text h6 size={15} color="white" style={{ margin: 0 }}>
                {text}
            </Text>
        </div>
    );
};
const list = [
  {
    title: 'Start',
    img: '/images/start-300x300.png',
    desc: '勉強を始める'
  },
  {
    title: 'Finished',
    img: '/images/start-300x300.png',
    desc: '勉強を終わりにする'
  }]


  return (
    <NextUIProvider>
    <div className={styles.container}>
      <Head>
        <title>Study Space</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <Card css={{ px: '$4' }}>
          <Text
            h3
            size={30}
            css={{
              textGradient: '45deg, $blue500 -20%, $pink500 50%'
            }}
            weight="bold"
          >
            Would you like
          </Text>
          <Text
            h3
            size={30}
            css={{
              textGradient: '45deg, $purple500 -20%, $pink500 100%'
            }}
            weight="bold"
          >
            to study
          </Text>
          <Text
            h3
            size={30}
            css={{
              textGradient: '45deg, $yellow500 -20%, $red500 100%'
            }}
            weight="bold"
          >
            together??
          </Text>
        </Card>
        <Grid.Container gap={2} justify="center">
          {list.map((item, index) => (
            <Grid xs={6} sm={4} key={index}>
              <Card width="100%">
              <Card.Header justify="flex-start">
                  <Row justify="space-between">
                    
                    <Text weight={500} style={{ opacity: 0.6 }}>
                      {item.desc}
                    </Text>
                  </Row>        
              </Card.Header>
                <Card.Body css={{ p: 0 }}>
                  <Card.Image
                    objectFit="cover"
                    src={item.img}
                    width='50%'
                    height="auto"
                    alt={item.title}
                  />
                </Card.Body>
                
                <Grid width="100%">
                <Input label="Name" type="text" fullWidth/>
                <Spacer x={0.3}/>
                <Input fullWidth label="Date" type="date"/>
                <Spacer x={0.3}/>
                <Input fullWidth label="Time" type="time"/>
                <Spacer y={1}/>
                
                 <Button auto color="warning" css={{ px: '$13' }} rounded 
                 iconRight={<Iconly name="Send" set="bulk" primaryColor="Darkgreen"/>}>
                  Submit!!!　
                  </Button>
                
                  </Grid>
                
              <Spacer y={1} />
              </Card>
            </Grid>
          ))}
        </Grid.Container>
    </div>
    </NextUIProvider>
  )
}